name = "Lloyd"
version = "0.1.0"
defaultTargets = ["Lloyd"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[lean_lib]]
name = "Lloyd"
