.PHONY: build check cache

build:
	lake build

check:
	python3 scripts/check.py

cache:
	lake exe cache get Mathlib.MeasureTheory.Integral.Bochner.Basic Mathlib.Analysis.SpecialFunctions.Pow.Real Mathlib.Tactic Mathlib.MeasureTheory.Integral.IntervalIntegral.AbsolutelyContinuousFun Mathlib.Analysis.Calculus.ContDiff.RCLike Mathlib.Analysis.SpecialFunctions.ExpDeriv Mathlib.Topology.MetricSpace.HausdorffDistance Mathlib.Analysis.Convex.Integral Mathlib.MeasureTheory.Integral.Lebesgue.Map Mathlib.MeasureTheory.Constructions.BorelSpace.Metric Mathlib.Algebra.Module.ZLattice.Basic Mathlib.Analysis.Normed.Group.Quotient Mathlib.Analysis.InnerProductSpace.PiL2 Mathlib.MeasureTheory.Measure.Haar.InnerProductSpace Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls Mathlib.Analysis.InnerProductSpace.Calculus Mathlib.MeasureTheory.Integral.Bochner.ContinuousLinearMap Mathlib.MeasureTheory.Measure.Real
