import Lloyd.Geometry.CellMeasure
import Mathlib.Algebra.Module.ZLattice.Basic
import Mathlib.Analysis.Normed.Group.Quotient

/-!
# Cell geometry for a genuine full-rank lattice

The lattice is the integer span of an arbitrary real basis. Thus these results
apply to general flat tori, not only the square torus. Separation and covering
are derived from this lattice and the finite configuration, not assumed.
-/

open MeasureTheory Metric Set Filter Topology

namespace Lloyd

variable {E : Type*} [NormedAddCommGroup E]

/-- Finite unions of closed discrete sets are closed and discrete. -/
theorem closed_discrete_iUnion {ι : Type*} [Finite ι] {s : ι → Set E}
    (hclosed : ∀ i, IsClosed (s i)) (hdiscrete : ∀ i, IsDiscrete (s i)) :
    IsClosed (⋃ i, s i) ∧ IsDiscrete (⋃ i, s i) := by
  have hc : ∀ i, (s i)ᶜ ∈ codiscrete E := by
    intro i
    apply compl_mem_codiscrete_iff.mpr
    exact ⟨hclosed i, (hdiscrete i).to_subtype⟩
  have hI := Filter.iInter_mem.mpr hc
  have hU : (⋃ i, s i)ᶜ ∈ codiscrete E := by simpa only [compl_iUnion] using hI
  obtain ⟨hcl, hd⟩ := compl_mem_codiscrete_iff.mp hU
  exact ⟨hcl, ⟨hd⟩⟩

/-- A closed discrete set has a positive separation from each of its points. -/
theorem exists_separation_of_closed_discrete {s : Set E}
    (hclosed : IsClosed s) (hdiscrete : IsDiscrete s) (p : E) :
    ∃ r > 0, ∀ q ∈ s, q ≠ p → 2 * r ≤ dist p q := by
  have hd := (isClosed_and_discrete_iff.mp ⟨hclosed, hdiscrete⟩) p
  rw [disjoint_principal_right] at hd
  obtain ⟨ε, hε, hball⟩ := Metric.mem_nhdsWithin_iff.mp hd
  refine ⟨ε / 2, by positivity, ?_⟩
  intro q hq hne
  by_contra hn
  have hdist : dist q p < ε := by rw [dist_comm]; linarith
  exact hball ⟨hdist, hne⟩ hq

/-- Periodic sites form a closed discrete set when there are finitely many generators. -/
theorem periodicSites_closed_discrete {ι : Type*} [Finite ι]
    (Λ : AddSubgroup E) [DiscreteTopology Λ] (x : ι → E) :
    IsClosed (periodicSites Λ x) ∧ IsDiscrete (periodicSites Λ x) := by
  have heq : periodicSites Λ x = ⋃ i, (fun k : E => x i + k) '' (Λ : Set E) := by
    ext y
    simp only [periodicSites, mem_range, Prod.exists, mem_iUnion, mem_image]
    constructor
    · rintro ⟨i, k, rfl⟩
      exact ⟨i, k, k.property, rfl⟩
    · rintro ⟨i, k, hk, rfl⟩
      exact ⟨i, ⟨k, hk⟩, rfl⟩
  rw [heq]
  have hc : IsClosed (Λ : Set E) := inferInstance
  have hd : IsDiscrete (Λ : Set E) := DiscreteTopology.isDiscrete
  exact closed_discrete_iUnion
    (fun i => (Homeomorph.addLeft (x i)).isClosedMap _ hc)
    (fun i => hd.image (Homeomorph.addLeft (x i)).isEmbedding)

variable [NormedSpace ℝ E] {κ : Type*} [Fintype κ]

/-- Full-rank lattice generated by a real basis. -/
def basisLattice (b : Module.Basis κ ℝ E) : AddSubgroup E :=
  (Submodule.span ℤ (Set.range b)).toAddSubgroup

instance basisLattice_discrete (b : Module.Basis κ ℝ E) : DiscreteTopology (basisLattice b) :=
  inferInstanceAs (DiscreteTopology (Submodule.span ℤ (Set.range b)).toAddSubgroup)

/-- Rounding coordinates in a lattice basis gives a configuration-independent
covering bound, using just one generator and all of its lattice translates. -/
theorem periodicSites_covering_bound {ι : Type*} (b : Module.Basis κ ℝ E)
    (x : ι → E) (i : ι) (y : E) :
    infDist y (periodicSites (basisLattice b) x) ≤ ∑ k, ‖b k‖ := by
  let k := ZSpan.floor b (y - x i)
  have hk : x i + (k : E) ∈ periodicSites (basisLattice b) x := ⟨(i, k), rfl⟩
  calc
    _ ≤ dist y (x i + (k : E)) := infDist_le_dist_of_mem hk
    _ = ‖ZSpan.fract b (y - x i)‖ := by
      rw [dist_eq_norm, ZSpan.fract_apply]
      congr 1
      dsimp [k]
      abel
    _ ≤ ∑ j, ‖b j‖ := ZSpan.norm_fract_le b _

variable [ProperSpace E]

/-- Lifted cells of every finite periodic configuration are compact. -/
theorem periodicCell_isCompact {ι : Type*} (b : Module.Basis κ ℝ E)
    (x : ι → E) (i : ι) : IsCompact (periodicCell (basisLattice b) x i) := by
  apply isCompact_voronoiCell (R := ∑ k, ‖b k‖)
  · exact ⟨(i, (0 : basisLattice b)), by simp⟩
  · exact periodicSites_covering_bound b x i

variable [MeasurableSpace E] [BorelSpace E] {μ : Measure E}
    [IsLocallyFiniteMeasure μ] [Measure.IsOpenPosMeasure μ]

/-- Positive finite cell volume and integrability, now derived for an actual
lattice. There are no assumed cell-volume, separation, or covering estimates. -/
theorem periodicCell_measure_properties {ι : Type*} [Finite ι]
    (b : Module.Basis κ ℝ E) (x : ι → E) (i : ι) :
    μ (periodicCell (basisLattice b) x i) ≠ 0 ∧
    μ (periodicCell (basisLattice b) x i) ≠ ⊤ ∧
    IntegrableOn (fun y : E => y) (periodicCell (basisLattice b) x i) μ := by
  obtain ⟨hc, hd⟩ := periodicSites_closed_discrete (basisLattice b) x
  obtain ⟨r, hr, hsep⟩ := exists_separation_of_closed_discrete hc hd (x i)
  exact voronoiCell_measure_properties
    (show x i ∈ periodicSites (basisLattice b) x from ⟨(i, 0), by simp⟩)
    hr hsep (periodicSites_covering_bound b x i)

end Lloyd
